apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsdemo
  labels:
    app: devopsdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsdemo
  template:
    metadata:
      labels:
        app: devopsdemo
    spec:
      containers:
      - name: devopsdemo
        image: balarara/devopsdemo
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: devopsdemo-svc
spec:
  type: NodePort
  selector:
    app: devopsdemo
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30002
